name: deploy

on:
  workflow_dispatch:
    inputs:
      lib_name:
        type: choice
        description: 'library names'
        required: true
        options:
          - simple_msteams
          - simple_sharepoint
          - simple_sftp
          - simple_sdcm
          - simple_ip_tools
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      working-directory: ${{ github.event.inputs.lib_name }}
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r requirements.txt

    - name: Build and publish
      working-directory: ${{ github.event.inputs.lib_name }}
      run: python setup.py bdist_wheel

    - name: Publish package distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN}}
        packages-dir: ${{ github.event.inputs.lib_name }}/dist
